<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>
<<include ticks.conf>>

<image>
<<include etc/image.conf>>
#file  = circos.png
#radius = 1500p
</image>

karyotype = karyotype.txt

########################################

<ideogram>

show_label       = yes
label_font       = default 
label_radius     = 1r + 120p
label_size       = 40
label_parallel   = yes

<spacing>
default = 0.005r
</spacing>

radius*    = 0.85r
thickness = 20p
fill      = yes
color = black
</ideogram>

########################################

<plots>

########################
# gene annotation ring
########################

<plot>
type = tile
file = genes_fwd_strand.txt
r1   = 0.97r
r0   = 0.92r
color = dgrey
layers = 1
margin      = 0.05u
orientation = center
stroke_thickness = 1
stroke_color     = dgrey
thickness = 50
padding = 8
</plot>

<plot>
type = tile
file = genes_rev_strand.txt
r1   = 0.90r
r0   = 0.85r
color = dgrey
layers = 1
margin = 0.05u
orientation = center
stroke_thickness = 1
stroke_color = dgrey
thickness = 50
padding = 8
</plot>

############################
### INSERTION SITE PLOTS ###
############################

<plot>
type = histogram
file = insertions_fwd_strand_5kb.bed
r1   = 0.80r
r0   = 0.55r
color = vdred
fill_color = vdred
thickness = 0.5
</plot>

<plot>
type = histogram
file = insertions_rev_strand_5kb.bed
r1   = 0.55r
r0   = 0.30r
orientation = in
color = orange
fill_color = orange
thickness = 0.5
</plot>

##################
### oriC marker ###
##################

<plot>
type = scatter
file = oriC.txt
r1 = 0.84r
r0 = 0.81r
color = blue
stroke_color = blue
stroke_thickness = 2
glyph = circle
glyph_size = 20
</plot>

##################
### oriC label ###
##################

<plot>
type = text
file = oriC_label.txt
r0 = 1.05r
r1 = 1.15r
label_size = 30p
label_font = bold
color = blue
orientation = out
</plot>





</plots>

